//@ sourceMappingURL=main-popup.map
// Generated by CoffeeScript 1.6.1
(function() {

  require.config({
    paths: {
      "jquery": "lib/jquery"
    },
    shim: {
      app: ["jquery"]
    }
  });

  require(["popup"], function(Popup) {
    return new Popup();
  });

}).call(this);
