//@ sourceMappingURL=main-app.map
// Generated by CoffeeScript 1.6.1
(function() {

  require.config({
    paths: {
      "jquery": "lib/jquery"
    },
    shim: {
      app: ["jquery"]
    }
  });

  require(["app"], function(App) {
    return new App();
  });

}).call(this);
