//@ sourceMappingURL=popup.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(["jquery"], function($) {
    var Popup;
    return Popup = (function() {

      Popup.prototype._query = 'broken tent';

      Popup.prototype._photos = null;

      function Popup() {
        console.log('Running Popup...');
        this._getPhotos();
      }

      Popup.prototype._getPhotos = function() {
        var req, url;
        url = 'https://secure.flickr.com/services/rest/?method=flickr.photos.search&format=json&api_key=d54e08aa66cbb8297a16758b1ea911be&text=' + encodeURIComponent(this._query) + '&safe_search=1&content_type=1&sort=relevance&per_page=40&nojsoncallback=1';
        req = new XMLHttpRequest();
        req.open("GET", url, true);
        req.onload = this._loadPhotos;
        return req.send(null);
      };

      Popup.prototype._loadPhotos = function(e) {
        var farmId, i, img, photoId, photos, secret, serverId, src, _i, _ref, _results;
        this._photos = JSON.parse(e.target.response);
        photos = this._photos.photos.photo;
        _results = [];
        for (i = _i = 0, _ref = photos.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          farmId = photos[i].farm;
          serverId = photos[i].server;
          photoId = photos[i].id;
          secret = photos[i].secret;
          src = "http://farm" + farmId + ".staticflickr.com/" + serverId + "/" + photoId + "_" + secret + ".jpg";
          img = $('<img>', {
            src: src
          });
          _results.push($('.photos').append(img));
        }
        return _results;
      };

      return Popup;

    })();
  });

}).call(this);
